name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  
  notification:
    name: Notificación Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Notify to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.NOTIFY_CHAT }}
          token: ${{ secrets.NOTIFY_SIGNKEY }}
          message: |
            ${{ github.actor }} hizo un push a master/main:
            Mensaje: 
            ${{ github.event.commits[0].message }}
            _______________________________________
            Repositorio: ${{ github.repository }}
        
  docker:
    name: Despliegue Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Dependencias de composer
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
      - name: Instalacion de yarn
        run: yarn
      - name: Generacion de key
        run: php artisan key:generate
      - name: Despliegue de yarn en producción
        run: yarn prod
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: set lower case repo name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.event.repository.name }}'
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/${{env.REPO_LC}}:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/${{env.REPO_LC}}:latest

      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}